image: node:14.6.0
cache:
  paths:
    - node_modules/
pages:
  script:
    - npm install
    - npm install @babel/core babel-loader html-webpack-plugin webpack webpack-cli webpack-dev-server --save-dev
    - npm install copy-webpack-plugin --save-dev
    - npm run build
    - mv dist public

  artifacts:
    paths:
      - public

  only:
    - master
